trigger:
  branches:
    include:
      - main

pr:
  - main
  - releases/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'asp_dot_net_docker'
  buildConfiguration: 'Release'
  hosted_agent: ubuntu-latest
  dockerRepo: 'khangeshmatte123/dotnet'
  System.AccessToken: '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'

stages:

- template: templates/build.yml

- template: templates/docker-pipeline.yml

- template: templates/test.yml

- template: templates/staging.yml

- template: templates/deploy.yml

