trigger:
- main
- feature/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy image
  jobs: 
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Building and running docker image using docker compose"
        docker build -t weatherapi:$(tag) .
      displayName: Build and Push Docker Image
    - script: |
        echo "Running weatherapi using docker compose"
        docker-compose -f docker-compose.yml up -d
      displayName: Run Docker Compose
