trigger:
- main
- feature/*

pr:
- none

resources:
- repo: self 

stages:
- stage: Linters
  displayName: Linter check for the present file
  jobs:
  - job: yamllint
    displayName: YAML Lint
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Installing yamllint"
        sudo apt-get update
        sudo apt-get install -y yamllint
        echo "Running yamllint on .yaml files"
        yamllint **/*.yaml || true
        echo "Running yamllint on .yml files"
        yamllint **/*.yml || true
      displayName: Run yamllint
      

