trigger:
- main
- feature/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'weatherapi'
  containerRegistry: 'asp_dot_net_docker'

stages:
- stage: Login
  displayName: Login docker
  jobs:
  - job: login
    displayName: Login to docker registery
    pool:
      vmImage: ubuntu-latest
      steps:
      - script: |
          echo "logging into the container registry"
        env: 
          DOCKER_USERNAME: $(dockerUsername)
          DOCKER_PASSWORD: $(dockerPassword)

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)


- stage: Deploy
  displayName: Deploy image
  jobs: 
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(containerRegistry)
        repository: $(imageName)
        command: 'push'
        tags: |
          $(tag)
      displayName: Build and Push Docker Image
    - script: |
        echo "Running weatherapi using docker compose"
    - task: DockerCompose@0
      inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: $(containerRegistry)
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: 'docker-compose -f docker-compose.yml up -d'
      displayName: Run Docker Compose
