trigger:
  branches:
    include:
      - main

pr:
  - none

resources:
  pipelines:
    - pipeline: manualTrigger
      source: Application_Hosting
      trigger: none

variables:
  - group: New_variable_group

stages:

- template: templates/build.yml

- template: templates/docker-pipeline.yml

- template: templates/test.yml

- template: templates/staging.yml

- template: templates/deploy.yml

