trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

resources:
- repo: self

pipelines:
  - pipeline: manualTrigger
    source: Application_Hosting
    trigger: none

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'asp_dot_net_docker'
  buildConfiguration: 'Release'
  hosted_agent: ubuntu-latest
  dockerRepo: 'khangeshmatte123/dotnet'

stages:

- template: templates/build.yml

- template: templates/docker-pipeline.yml

- template: templates/test.yml

- template: templates/staging.yml

- template: templates/deploy.yml

