trigger:
  branches:
    include:
      - main

pr:
  - main
  - releases/*
  - feature/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'asp_dot_net_docker'

stages:

- template: templates/build.yml

- template: templates/test.yml

- template: templates/staging.yml

- template: templates/release.yml

- template: templates/deploy.yml

