trigger:
- main
- feature/*

pr:
- none

resources:
- repo: self 

stages:
- stage: Linetrs
  display_name: Linter check for the present file
  Jobs: 
  - job: Linters
  pool:
  -  vmImage: 'ubuntu-latest'
  steps:
  - scripts: |
      echo "Installing yamllint"
      sudo apt-get update
      sudo apt-get install -y yamllint
      echo "Running yamllint"
      yamllint **/*.yaml
    displayName: Run yamllint

