trigger:
- main
- feature/*

pr:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'asp_dot_net_docker'

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      displayName: use dotnet asp core
      inputs:
        pacakgeType: sdk
        version: '8.0.x'

    - script: |
        dotnet restore weatherapi/weatherapi.csproj
      displayName: restore packages

    - script: |
        dotnet build weatherapi/weatherapi.csproj --configuration Debug
      displayName: build the project#

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: $(containerRegistry)
        repository: 'khangeshmatte123/dotnet'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
           $(tag)

- stage: Deploy
  displayName: Deploy Image
  dependsOn: Build
  jobs: 
  - job: deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Running weatherapi using docker compose"
    - task: DockerCompose@0
      displayName: Run Docker Compose
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(containerRegistry)
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up -d'
        build: true
