trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
  - job: Lint
    displayName: 'Lint Markdown Files'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y ruby
          sudo gem install mdl
        displayName: 'Install mdl Linter'

      - script: |
          mdl .
        displayName: 'Run mdl Linter'
        continueOnError: false
