trigger:
- main
- feature/*

pr:
- none

resources:
- repo: self 

stages:
- stage: Linters
  displayName: Linter check for the present file
  jobs:
  - job: yamllint
    displayName: YAML Lint
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Installing yamllint"
        sudo apt-get update
        sudo apt-get install -y yamllint
        echo "Running yamllint on .yaml files"
        find . -type f -name '*.yaml' -exec yamllint {} +
        echo "Running yamllint on .yml files"
        find . -type f -name '*.yml' -exec yamllint {} +
      displayName: Run yamllint

  - job: dotnetlint
    displayName: dotnet Lint
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Installing .NET format tool"
        dotnet tool install -g dotnet-format
        echo "Running .NET format"
        dotnet-format --check **/*.cs
      displayName: Run .NET format