stages:
- stage: Build
  displayName: Build
  jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: $(hosted_agent)
    steps:
    - checkout: self
      fetchDepth: 0

    - task: UseDotNet@2
      displayName: use dotnet asp core
      inputs:
        packageType: sdk
        version: '8.0.x'

    - script: |
        dotnet restore weatherapi/weatherapi.csproj
      displayName: restore packages
    
    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: '$(SonarCloud)'
        organization: '$(SonarOrganization)'
        scannerMode: 'MSBuild'
        projectKey: '$(projectKey)'
        projectName: 'Intial_app_dotnet'

    - script: |
        dotnet build weatherapi/weatherapi.csproj --configuration $(buildConfiguration)
      displayName: build the project

    - script: |
        dotnet publish weatherapi/weatherapi.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish $(buildConfiguration)'

    - task: SonarCloudAnalyze@2
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarCloudPublish@2
      inputs:
        pollingTimeoutSec: '300'

    - task: PublishBuildArtifacts@1