stages:
- stage: Deploy
  displayName: Deploy Image
  dependsOn: Staging
  jobs: 
  - job: deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Running weatherapi using docker compose"
    - task: DockerCompose@0
      displayName: Run Docker Compose
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(containerRegistry)
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up -d'
        build: false

     # Check container status
    - script: |
        docker ps -a
      displayName: Check Container Status

    - script: |
        docker-compose logs
      displayName: Inspect Container Logs

    # Health check
    - script: |
        curl -f http://localhost:8081/api/weather || exit 1
      displayName: Health Check