stages:
- stage: BuildAndPushDockerImage
  displayName: Build and Push Docker Image
  dependsOn: Build
  jobs:
  - job: dockerBuildAndPush
    displayName: Build and Push Docker Image
    pool:
      vmImage: '$(hosted_agent)'
    steps:
    - task: Docker@2
      displayName: Build docker image
      inputs:
        command: 'build'
        containerRegistry: $(containerRegistry)
        repository: $(dockerRepo)
        Dockerfile: '**/Dockerfile'
        tags: |
            $(tag)
            latest
    
    - task: Docker@2
      displayName: Push docker image
      inputs:
        containerRegistry: $(containerRegistry)
        repository: $(dockerRepo)
        command: 'push'
        Dockerfile: '**/Dockerfile'
        tags: |
            $(tag)
            latest
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

    - script: |
        git tag -a v$(Build.BuildId) -m "Release v$(Build.BuildId)"
        git push origin --tags
      displayName: 'Tag Source Code with Version Number'
      env:
        GIT_AUTH_TOKEN: github.com_khangesh9420

