stages:
- stage: Staging
  displayName: Staging Deploy
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: stagingDeploy
    displayName: Creating staging enviornment
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Running Staging before deployment"
    - task: DockerCompose@0
      displayName: Run Docker Compose
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(containerRegistry)
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up -d'
        build: false